### ISSUE TITLE
Web analytics

### ISSUE THREAD

**Issue by michzimny** [up2university/DSpace#5]
Please add Matomo tracking code to all pages as documented here:
https://wiki.geant.org/display/UP2U/Web+Analytics

**Comment by lionick** [comment]
I added Matomo tracking code to both instances test and production according to the document.

**Comment by michzimny** [comment]
@lionick, you should use different codes for different instances, as in the wiki page. As far as I can see, you have now the code with matomo-test.js in both instances. You should have the code with matomo-production.js in the production instance.

**Comment by lionick** [comment]
Hi Michal 
I am using matomo-production. Check this screenshot below:

![screenshot from 2019-01-15 12-34-22](https://user-images.githubusercontent.com/44701697/51175090-00f09680-18c2-11e9-9707-e9ad2b5e3680.png)

**Comment by michzimny** [comment]
You're right, sorry. 

I've checked eduOER, and my comment was meant for that tool :-)
